[global]
# 开发模式配置
developmentMode = false

[server]
# 服务器配置
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
# 浏览器配置
gatherUsageStats = false
showErrorDetails = true

[theme]
# 主题配置
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
